# Generated by Django 4.0.1 on 2022-01-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('img_url', models.CharField(max_length=256)),
                ('founded', models.IntegerField()),
                ('founder', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_name', models.CharField(max_length=256)),
                ('weapon', models.CharField(max_length=256)),
                ('fight_ability', models.CharField(max_length=256)),
                ('real_name', models.CharField(max_length=256)),
                ('dob', models.DateField()),
                ('img_url', models.CharField(max_length=256)),
                ('is_villain', models.BooleanField()),
                ('is_hero', models.BooleanField()),
                ('background', models.CharField(max_length=256)),
                ('origin', models.CharField(max_length=256)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='universe.publisher')),
            ],
        ),
    ]
