# Generated by Django 4.0.1 on 2022-01-27 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='character',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_hero',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_villain',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='origin',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='character',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='universe.publisher'),
        ),
    ]
