# Generated by Django 4.0.1 on 2022-01-27 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0003_alter_character_dob_alter_character_is_hero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='dob',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_hero',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='is_villain',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
