# Generated by Django 4.0.1 on 2022-01-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universe', '0004_alter_character_dob_alter_character_is_hero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='universe.publisher'),
        ),
    ]
